Xp addition
Ifera/ScoreHudX pull request #11
Opened 2021-07-18 09:05 UTC by MrNinja008

2021-07-18 11:09 UTC, Ifera requested changes
Please do the changes requested. The PR will only be merged once all changes have been done.

2021-07-18 11:09 UTC, Ifera commented on BasicScore/src/Ifera/BasicScore/Main.php
> +                                (new PlayerTagUpdateEvent($player, new ScoreTag("basicscore.xp", strval($player->getXpLevel()))))->call();
Bad formatting

2021-07-18 11:09 UTC, Ifera commented on BasicScore/src/Ifera/BasicScore/listeners/EventListener.php
> +        }
Same as above, the formatting is all over the place.

2021-07-18 11:09 UTC, Ifera commented on BasicScore/src/Ifera/BasicScore/listeners/TagResolveListener.php
> +                        case "xp":
bad formatting again

2021-07-18 11:09 UTC, Ifera commented on BasicScore/src/Ifera/BasicScore/listeners/TagResolveListener.php
missing `break` statement.

2021-07-18 11:09 UTC, Ifera commented on BasicScore/README.md
> +|`{basicscore.xp}`|Display Xp Level Of Player|
Don't capitalize the starting letter of every word.

2021-07-18 13:35 UTC, MrNinja008 commented
Sloved Everything lol

2021-07-19 16:45 UTC, Ifera commented
Superseded by #16

2021-07-19 16:45 UTC, closed without merging